### ISSUE TITLE
hexo new post 后，hexo generate error

### ISSUE THREAD

**Issue by miracleqi** [Sariay/hexo-theme-Annie#16]
$ hexo generate                                                                                        
INFO  Start processing                                                                                 
INFO  Files loaded in 218 ms                                                                           
ERROR E:\blog\themes\Annie\layout\post.ejs:1                                                           
 >> 1| <%- partial('_partial/post', {post: page}) %>                                                   
                                                                                                       
E:\blog\themes\Annie\layout\_partial\post.ejs:43                                                       
    41|                 
                                               
    42|                         
                                  
 >> 43|                                 <%- partial('post-relate') %>                                  
    44|                         
                                                                 
    45|                         
                                  
    46|                                 <%- partial('third/comment') %>                                
                                                                                                       
E:\blog\themes\Annie\layout\_partial\post-relate.ejs:1                                                 
 >> 1| <%                                                                                              
    2|  var currentPostTitle = post.title,                                                             
    3|          relatePostsArry = [],                                                                  
    4|          result =[],                                                                            
                                                                                                       
Illegal break statement                                                                                
SyntaxError: E:\blog\themes\Annie\layout\post.ejs:1                                                    
 >> 1| <%- partial('_partial/post', {post: page}) %>                                                   
                                                                                                       
E:\blog\themes\Annie\layout\_partial\post.ejs:43                                                       
    41|                 
                                               
    42|                         
                                  
 >> 43|                                 <%- partial('post-relate') %>                                  
    44|                         
                                                                 
    45|                         
                                  
    46|                                 <%- partial('third/comment') %>                                
                                                                                                       
E:\blog\themes\Annie\layout\_partial\post-relate.ejs:1                                                 
 >> 1| <%                                                                                              
    2|  var currentPostTitle = post.title,                                                             
    3|          relatePostsArry = [],                                                                  
    4|          result =[],                                                                            
                                                                                                       
Illegal break statement                                                                                
    at eval (eval at compile (E:\blog\node_modules\ejs\lib\ejs.js:618:12), :65:12)          
    at returnedFn (E:\blog\node_modules\ejs\lib\ejs.js:653:17)                                         
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\blog\node_modules\hexo\lib\theme\vi
ew.js:121:22)                                                                                          
    at Theme._View.View.View.renderSync (E:\blog\node_modules\hexo\lib\theme\view.js:49:23)            
    at Object.partial (E:\blog\node_modules\hexo\lib\plugins\helper\partial.js:38:15)                  
    at eval (eval at compile (E:\blog\node_modules\ejs\lib\ejs.js:618:12), :50:17)          
    at returnedFn (E:\blog\node_modules\ejs\lib\ejs.js:653:17)                                         
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\blog\node_modules\hexo\lib\theme\vi
ew.js:121:22)                                                                                          
    at Theme._View.View.View.renderSync (E:\blog\node_modules\hexo\lib\theme\view.js:49:23)            
    at Object.partial (E:\blog\node_modules\hexo\lib\plugins\helper\partial.js:38:15)                  
    at eval (eval at compile (E:\blog\node_modules\ejs\lib\ejs.js:618:12), :9:17)           
    at returnedFn (E:\blog\node_modules\ejs\lib\ejs.js:653:17)                                         
    at Theme._View.View._compiled.locals [as _compiled] (E:\blog\node_modules\hexo\lib\theme\view.js:12
5:48)                                                                                                  
    at Theme._View.View.View.render (E:\blog\node_modules\hexo\lib\theme\view.js:30:15)                
    at route.set (E:\blog\node_modules\hexo\lib\hexo\index.js:394:29)                                  
    at tryCatcher (E:\blog\node_modules\bluebird\js\release\util.js:16:23)                             
    at E:\blog\node_modules\bluebird\js\release\method.js:15:34                                        
    at RouteStream._read (E:\blog\node_modules\hexo\lib\hexo\router.js:134:3)                          
    at RouteStream.Readable.read (_stream_readable.js:442:10)                                          
    at resume_ (_stream_readable.js:822:12)                                                            
    at _combinedTickCallback (internal/process/next_tick.js:138:11)                                    
    at process._tickCallback (internal/process/next_tick.js:180:9)                                     
ERROR E:\blog\themes\Annie\layout\post.ejs:1                                                           
 >> 1| <%- partial('_partial/post', {post: page}) %>                                                   
                                                                                                       
E:\blog\themes\Annie\layout\_partial\post.ejs:43                                                       
    41|                 
                                               
    42|                         
                                  
 >> 43|                                 <%- partial('post-relate') %>                                  
    44|                         
                                                                 
    45|                         
                                  
    46|                                 <%- partial('third/comment') %>                                
                                                                                                       
E:\blog\themes\Annie\layout\_partial\post-relate.ejs:1                                                 
 >> 1| <%                                                                                              
    2|  var currentPostTitle = post.title,                                                             
    3|          relatePostsArry = [],                                                                  
    4|          result =[],                                                                            
                                                                                                       
Illegal break statement                                                                                
SyntaxError: E:\blog\themes\Annie\layout\post.ejs:1                                                    
 >> 1| <%- partial('_partial/post', {post: page}) %>                                                   
                                                                                                       
E:\blog\themes\Annie\layout\_partial\post.ejs:43                                                       
    41|                 
                                               
    42|                         
                                  
 >> 43|                                 <%- partial('post-relate') %>                                  
    44|                         
                                                                 
    45|                         
                                  
    46|                                 <%- partial('third/comment') %>                                
                                                                                                       
E:\blog\themes\Annie\layout\_partial\post-relate.ejs:1                                                 
 >> 1| <%                                                                                              
    2|  var currentPostTitle = post.title,                                                             
    3|          relatePostsArry = [],                                                                  
    4|          result =[],                                                                            
                                                                                                       
Illegal break statement                                                                                
    at eval (eval at compile (E:\blog\node_modules\ejs\lib\ejs.js:618:12), :65:12)          
    at returnedFn (E:\blog\node_modules\ejs\lib\ejs.js:653:17)                                         
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\blog\node_modules\hexo\lib\theme\vi
ew.js:121:22)                                                                                          
    at Theme._View.View.View.renderSync (E:\blog\node_modules\hexo\lib\theme\view.js:49:23)            
    at Object.partial (E:\blog\node_modules\hexo\lib\plugins\helper\partial.js:38:15)                  
    at eval (eval at compile (E:\blog\node_modules\ejs\lib\ejs.js:618:12), :50:17)          
    at returnedFn (E:\blog\node_modules\ejs\lib\ejs.js:653:17)                                         
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\blog\node_modules\hexo\lib\theme\vi
ew.js:121:22)                                                                                          
    at Theme._View.View.View.renderSync (E:\blog\node_modules\hexo\lib\theme\view.js:49:23)            
    at Object.partial (E:\blog\node_modules\hexo\lib\plugins\helper\partial.js:38:15)                  
    at eval (eval at compile (E:\blog\node_modules\ejs\lib\ejs.js:618:12), :9:17)           
    at returnedFn (E:\blog\node_modules\ejs\lib\ejs.js:653:17)                                         
    at Theme._View.View._compiled.locals [as _compiled] (E:\blog\node_modules\hexo\lib\theme\view.js:12
5:48)                                                                                                  
    at Theme._View.View.View.render (E:\blog\node_modules\hexo\lib\theme\view.js:30:15)                
    at route.set (E:\blog\node_modules\hexo\lib\hexo\index.js:394:29)                                  
    at tryCatcher (E:\blog\node_modules\bluebird\js\release\util.js:16:23)                             
    at E:\blog\node_modules\bluebird\js\release\method.js:15:34                                        
    at RouteStream._read (E:\blog\node_modules\hexo\lib\hexo\router.js:134:3)                          
    at RouteStream.Readable.read (_stream_readable.js:442:10)                                          
    at resume_ (_stream_readable.js:822:12)                                                            
    at _combinedTickCallback (internal/process/next_tick.js:138:11)                                    
    at process._tickCallback (internal/process/next_tick.js:180:9)                                     
INFO  Generated: searchVersion.txt                                                                     
INFO  Generated: content.json                                                                          
INFO  Generated: index.html                                                                            
INFO  Generated: categories/index.html                                                                 
INFO  Generated: about/index.html                                                                      
INFO  Generated: tags/index.html                                                                       
INFO  Generated: archives/index.html                                                                   
INFO  Generated: gallery/index.html                                                                    
INFO  Generated: img/logo.png                                                                          
INFO  Generated: gallery/images/default-skin.svg                                                       
INFO  Generated: gallery/natural.css                                                                   
INFO  Generated: gallery/natural-gallery.full.css                                                      
INFO  Generated: gallery/data.json                                                                     
INFO  Generated: gallery/natural-gallery.full.js                                                       
INFO  Generated: img/cart_cover.jpg                                                                    
INFO  Generated: gallery/images/preloader.gif                                                          
INFO  Generated: img/favicon.ico                                                                       
INFO  Generated: gallery/images/default-skin.png                                                       
INFO  Generated: archives/2018/12/index.html                                                           
INFO  Generated: archives/2018/index.html                                                              
INFO  Generated: css/App.css                                                                           
INFO  Generated: css/Annie.css                                                                         
INFO  Generated: css/comment.css                                                                       
INFO  Generated: css/archive.css                                                                       
INFO  Generated: css/page.css                                                                          
INFO  Generated: css/post.css                                                                          
INFO  Generated: css/toc.css                                                                           
INFO  Generated: css/nav.css                                                                           
INFO  Generated: css/style.css                                                                         
INFO  Generated: css/search.css                                                                        
INFO  Generated: js/chinese.js                                                                         
INFO  Generated: js/love.js                                                                            
INFO  Generated: js/main.js                                                                            
INFO  Generated: js/search.js                                                                          
INFO  Generated: js/leancloud.js                                                                       
INFO  Generated: js/valine.min.js                                                                      
INFO  Generated: js/vibrant.js                                                                         
INFO  Generated: js/ziploader.js                                                                       
INFO  Generated: js/jquery-2.1.1.min.js                                                                
INFO  Generated: js/motto.js                                                                           
INFO  Generated: img/1.jpg                                                                             
INFO  Generated: plugin/lightgallery/fonts/icomoon.ttf                                                 
INFO  Generated: plugin/lightgallery/fonts/icomoon.svg                                                 
INFO  Generated: plugin/lightgallery/fonts/icomoon.eot                                                 
INFO  Generated: plugin/lightgallery/fonts/icomoon.woff                                                
INFO  Generated: plugin/lightgallery/img/vimeo-play.png                                                
INFO  Generated: plugin/lightgallery/fonts/lg.eot                                                      
INFO  Generated: plugin/lightgallery/fonts/lg.svg                                                      
INFO  Generated: plugin/lightgallery/img/video-play.png                                                
INFO  Generated: plugin/lightgallery/img/loading.gif                                                   
INFO  Generated: plugin/lightgallery/fonts/lg.ttf                                                      
INFO  Generated: plugin/lightgallery/fonts/lg.woff                                                     
INFO  Generated: plugin/toc/katelog.min.js                                                             
INFO  Generated: plugin/lightgallery/img/youtube-play.png                                              
INFO  Generated: 2018/12/28/test/index.html                                                            
INFO  Generated: plugin/lightgallery/css/lightgallery.css                                              
INFO  Generated: img/poem1.png                                                                         
INFO  Generated: plugin/lightgallery/js/lightgallery-all.min.js                                        
INFO  Generated: 2018/12/27/hello-world/index.html                                                     
INFO  Generated: plugin/lightgallery/js/jquery-1.11.0.min.js                                           
INFO  Generated: img/2.jpg                                                                             
INFO  61 files generated in 233 m

**Comment by miracleqi** [comment]
作者已回复：
请将post-relate.ejs文件的第50行代码
if(ij >= distance)	break;
替换为
if(ij >= distance)	return;
