### ISSUE TITLE
“参数配置”引起的编译问题

### ISSUE THREAD

**Issue by Palpitation-github** [Sariay/hexo-theme-Annie#28]
ERROR D:\Blog\xj_D\themes\Annie\layout\layout.ejs:16
    14|                 <%- partial('_partial/head',{cache: true}) %>
    15|         <body>
 >> 16|                 <%- partial('_partial/header',{cache: true}) %>
    17|
    18|                 
    19|                 <main>

D:\Blog\xj_D\themes\Annie\layout\_partial\header.ejs:2
    1| 
 >> 2| <%
    3|  if(theme.preloader.enable) {
    4|          var animation = theme.preloader.animation;
    5| %>

Cannot read property 'enable' of undefined
TypeError: D:\Blog\xj_D\themes\Annie\layout\layout.ejs:16
    14|                 <%- partial('_partial/head',{cache: true}) %>
    15|         <body>
 >> 16|                 <%- partial('_partial/header',{cache: true}) %>
    17|
    18|                 
    19|                 <main>

D:\Blog\xj_D\themes\Annie\layout\_partial\header.ejs:2
    1| 
 >> 2| <%
    3|  if(theme.preloader.enable) {
    4|          var animation = theme.preloader.animation;
    5| %>

Cannot read property 'enable' of undefined

**Comment by Palpitation-github** [comment]
hexo s之后也报错
PS D:\Blog\xj_D> hexo s
INFO  Start processing
ERROR Theme config load failed.
ERROR Process failed: _config.yml
YAMLException: duplicated mapping key at line 156, column -291:
    local_search:
    ^
    at generateError (D:\Blog\xj_D\node_modules\js-yaml\lib\js-yaml\loader.js:165:10)
    at throwError (D:\Blog\xj_D\node_modules\js-yaml\lib\js-yaml\loader.js:171:9)
    at storeMappingPair (D:\Blog\xj_D\node_modules\js-yaml\lib\js-yaml\loader.js:320:7)
    at readBlockMapping (D:\Blog\xj_D\node_modules\js-yaml\lib\js-yaml\loader.js:1083:9)
    at composeNode (D:\Blog\xj_D\node_modules\js-yaml\lib\js-yaml\loader.js:1344:12)
    at readDocument (D:\Blog\xj_D\node_modules\js-yaml\lib\js-yaml\loader.js:1504:3)
    at loadDocuments (D:\Blog\xj_D\node_modules\js-yaml\lib\js-yaml\loader.js:1560:5)
    at Object.load (D:\Blog\xj_D\node_modules\js-yaml\lib\js-yaml\loader.js:1581:19)
    at Hexo.yamlHelper (D:\Blog\xj_D\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (D:\Blog\xj_D\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\Blog\xj_D\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.then.text (D:\Blog\xj_D\node_modules\hexo\lib\hexo\render.js:61:21)
    at tryCatcher (D:\Blog\xj_D\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Blog\xj_D\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Blog\xj_D\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Blog\xj_D\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Blog\xj_D\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (D:\Blog\xj_D\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\Blog\xj_D\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\Blog\xj_D\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\Blog\xj_D\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
Unhandled rejection TypeError: D:\Blog\xj_D\themes\Annie\layout\index.ejs:18
    16|
    17|         
 >> 18|         <%- partial('_partial/index-pure') %>
    19|
    20| <% } %>

D:\Blog\xj_D\themes\Annie\layout\_partial\index-pure.ejs:28
    26|                                         </span>
    27|                                         <%= __('split_line')%>
 >> 28|                                         <%- partial('post-like',{post: post}) %>
    29|                                         <%- partial('third/statistics', {module: 'leancloud'}) %>
    30|                                         <% if (theme.excerpt_link){ %>
    31|                                                 <span class="right">

D:\Blog\xj_D\themes\Annie\layout\_partial\post-like.ejs:4
    2|  var lean = theme.leancloud_count;
    3| %>
 >> 4| <% if( lean.enable && lean.visit_post.enable ){ %>
    5|     <span class="leancloud_visitors" id="<%- url_for(post.path) %>_visitors" data-url="<%- url_for(post.path) %>" data-title="<%- post.title %>">
    6|         <%= __('hits') %>
    7|         <i class="leancloud_visitors_count" id="leancloud_visitors_count">0</i>

Cannot read property 'enable' of undefined
    at eval (eval at compile (D:\Blog\xj_D\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:15:17)
    at returnedFn (D:\Blog\xj_D\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (D:\Blog\xj_D\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (D:\Blog\xj_D\node_modules\hexo\lib\theme\view.js:49:23)
    at Object.partial (D:\Blog\xj_D\node_modules\hexo\lib\plugins\helper\partial.js:38:15)
    at eval (eval at compile (D:\Blog\xj_D\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:41:17)
    at Model._Query.Query.Query.forEach (D:\Blog\xj_D\node_modules\warehouse\lib\query.js:42:5)
    at eval (eval at compile (D:\Blog\xj_D\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:11:19)
    at returnedFn (D:\Blog\xj_D\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (D:\Blog\xj_D\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (D:\Blog\xj_D\node_modules\hexo\lib\theme\view.js:49:23)
    at Object.partial (D:\Blog\xj_D\node_modules\hexo\lib\plugins\helper\partial.js:38:15)
    at eval (eval at compile (D:\Blog\xj_D\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:30:17)
    at returnedFn (D:\Blog\xj_D\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (D:\Blog\xj_D\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (D:\Blog\xj_D\node_modules\hexo\lib\theme\view.js:30:15)
    at route.set (D:\Blog\xj_D\node_modules\hexo\lib\hexo\index.js:394:29)
    at tryCatcher (D:\Blog\xj_D\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Blog\xj_D\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\Blog\xj_D\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:452:10)
    at resume_ (_stream_readable.js:899:12)

**Comment by Sariay** [comment]
```
Cannot read property 'enable' of undefined
```
你阅读一下error反馈！！！找不到参数**enable**

---

解决：

1.确保站点目录下_config.yml文件中的项目名和\themes\Annie中的**Annie**相同

2.去掉重复的参数

3.添加相应的参数

一般不需要进行2、3步骤

@voidmaker69

**Comment by Palpitation-github** [comment]
解决啦蟹蟹
