### ISSUE TITLE
[Question]：首页无法加载文章封面图片，node报错

### ISSUE THREAD

**Issue by Symbolk** [Sariay/hexo-theme-Annie#39]
本地测试和部署到服务器都无法显示首页文章封面图片，因为该部分代码报错，信息如下：
```sh
$ hexo s -p 8181
(node:30416) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  Start processing
ERROR Process failed: layout/_partial/index-cart.ejs
SyntaxError: Invalid or unexpected token in "D:\\Blog\\themes\\Annie\\layout\\_partial\\index-cart.ejs"
    at new Function (<anonymous>)
    at Object.exports.compile (D:\Blog\node_modules\ejs\lib\ejs.js:242:14)
    at Function.ejsRenderer.compile (D:\Blog\node_modules\hexo-renderer-ejs\lib\renderer.js:11:14)
    at Theme._View.View.View._precompile (D:\Blog\node_modules\hexo\lib\theme\view.js:119:29)
    at Theme._View.View.View (D:\Blog\node_modules\hexo\lib\theme\view.js:13:8)
    at new Theme._View.View (D:\Blog\node_modules\hexo\lib\theme\index.js:37:10)
    at Theme.setView (D:\Blog\node_modules\hexo\lib\theme\index.js:71:20)
    at D:\Blog\node_modules\hexo\lib\theme\processors\view.js:14:14
    at tryCatcher (D:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\Blog\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (D:\Blog\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (D:\Blog\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\Blog\node_modules\bluebird\js\release\promise.js:638:18)
    at D:\Blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at D:\Blog\node_modules\graceful-fs\graceful-fs.js:78:16
ERROR Process failed: layout/_partial/post-relate.ejs
SyntaxError: Invalid or unexpected token in "D:\\Blog\\themes\\Annie\\layout\\_partial\\post-relate.ejs"
    at new Function (<anonymous>)
    at Object.exports.compile (D:\Blog\node_modules\ejs\lib\ejs.js:242:14)
    at Function.ejsRenderer.compile (D:\Blog\node_modules\hexo-renderer-ejs\lib\renderer.js:11:14)
    at Theme._View.View.View._precompile (D:\Blog\node_modules\hexo\lib\theme\view.js:119:29)
    at Theme._View.View.View (D:\Blog\node_modules\hexo\lib\theme\view.js:13:8)
    at new Theme._View.View (D:\Blog\node_modules\hexo\lib\theme\index.js:37:10)
    at Theme.setView (D:\Blog\node_modules\hexo\lib\theme\index.js:71:20)
    at D:\Blog\node_modules\hexo\lib\theme\processors\view.js:14:14
    at tryCatcher (D:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\Blog\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (D:\Blog\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (D:\Blog\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\Blog\node_modules\bluebird\js\release\promise.js:638:18)
    at D:\Blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at D:\Blog\node_modules\graceful-fs\graceful-fs.js:78:16
ERROR Process failed: layout/_partial/plugin/toc.ejs
SyntaxError: Invalid or unexpected token in "D:\\Blog\\themes\\Annie\\layout\\_partial\\plugin\\toc.ejs"
    at new Function (<anonymous>)
    at Object.exports.compile (D:\Blog\node_modules\ejs\lib\ejs.js:242:14)
    at Function.ejsRenderer.compile (D:\Blog\node_modules\hexo-renderer-ejs\lib\renderer.js:11:14)
    at Theme._View.View.View._precompile (D:\Blog\node_modules\hexo\lib\theme\view.js:119:29)
    at Theme._View.View.View (D:\Blog\node_modules\hexo\lib\theme\view.js:13:8)
    at new Theme._View.View (D:\Blog\node_modules\hexo\lib\theme\index.js:37:10)
    at Theme.setView (D:\Blog\node_modules\hexo\lib\theme\index.js:71:20)
    at D:\Blog\node_modules\hexo\lib\theme\processors\view.js:14:14
    at tryCatcher (D:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\Blog\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (D:\Blog\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (D:\Blog\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\Blog\node_modules\bluebird\js\release\promise.js:638:18)
    at D:\Blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at D:\Blog\node_modules\graceful-fs\graceful-fs.js:78:16

```
附上运行环境：
```sh
D:\Blog
$ node -v
v8.9.4

D:\Blog
$ hexo -v
(node:14956) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
hexo: 3.2.2
hexo-cli: 2.0.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.7.0
node: 8.9.4
v8: 6.1.534.50
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

**Comment by Sariay** [comment]
可以给一个**线上链接**么

@Symbolk

**Comment by Symbolk** [comment]
@Sariay https://symbolk.com/

**Comment by Sariay** [comment]
index-cart.ejs等文件是否修改过！

这个问题应该不会出现的！

@Symbolk

**Comment by Symbolk** [comment]
> index-cart.ejs等文件是否修改过！
> 
> 这个问题应该不会出现的！
> 
> @Symbolk

没有呢，直接clone下来只修改了_config.xml

**Comment by Sariay** [comment]
**index-style: pure | cart**
index_style: cart

你换个主页试下呢 @Symbolk

**Comment by Symbolk** [comment]
> **index-style: pure | cart**
> index_style: cart
> 
> 你换个主页试下呢 @Symbolk

嗯嗯，pure是正常的，虽然控制台依然会有错误提示。请问你开发环境是怎样呢？看到有一个issue推测是windows平台的问题。

https://github.com/hexojs/hexo/issues/2890

**Comment by Sariay** [comment]
window平台的话，环境相差不大！

主题2018下半年开发的。

是否可以贴一下**hexo g**的执行结果，我再次查看一下相关的代码。

@Symbolk

**Comment by Symbolk** [comment]
@Sariay 以下是**hexo g**的执行结果：
```sh
$ hexo g
(node:41348) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  Start processing
ERROR Process failed: layout/_partial/index-cart.ejs
SyntaxError: Invalid or unexpected token in "D:\\Blog\\themes\\Annie\\layout\\_partial\\index-cart.ejs"
    at new Function (<anonymous>)
    at Object.exports.compile (D:\Blog\node_modules\ejs\lib\ejs.js:242:14)
    at Function.ejsRenderer.compile (D:\Blog\node_modules\hexo-renderer-ejs\lib\renderer.js:11:14)
    at Theme._View.View.View._precompile (D:\Blog\node_modules\hexo\lib\theme\view.js:119:29)
    at Theme._View.View.View (D:\Blog\node_modules\hexo\lib\theme\view.js:13:8)
    at new Theme._View.View (D:\Blog\node_modules\hexo\lib\theme\index.js:37:10)
    at Theme.setView (D:\Blog\node_modules\hexo\lib\theme\index.js:71:20)
    at D:\Blog\node_modules\hexo\lib\theme\processors\view.js:14:14
    at tryCatcher (D:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\Blog\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (D:\Blog\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (D:\Blog\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\Blog\node_modules\bluebird\js\release\promise.js:638:18)
    at D:\Blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at D:\Blog\node_modules\graceful-fs\graceful-fs.js:78:16
ERROR Process failed: layout/_partial/post-relate.ejs
SyntaxError: Invalid or unexpected token in "D:\\Blog\\themes\\Annie\\layout\\_partial\\post-relate.ejs"
    at new Function (<anonymous>)
    at Object.exports.compile (D:\Blog\node_modules\ejs\lib\ejs.js:242:14)
    at Function.ejsRenderer.compile (D:\Blog\node_modules\hexo-renderer-ejs\lib\renderer.js:11:14)
    at Theme._View.View.View._precompile (D:\Blog\node_modules\hexo\lib\theme\view.js:119:29)
    at Theme._View.View.View (D:\Blog\node_modules\hexo\lib\theme\view.js:13:8)
    at new Theme._View.View (D:\Blog\node_modules\hexo\lib\theme\index.js:37:10)
    at Theme.setView (D:\Blog\node_modules\hexo\lib\theme\index.js:71:20)
    at D:\Blog\node_modules\hexo\lib\theme\processors\view.js:14:14
    at tryCatcher (D:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\Blog\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (D:\Blog\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (D:\Blog\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\Blog\node_modules\bluebird\js\release\promise.js:638:18)
    at D:\Blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at D:\Blog\node_modules\graceful-fs\graceful-fs.js:78:16
ERROR Process failed: layout/_partial/plugin/toc.ejs
SyntaxError: Invalid or unexpected token in "D:\\Blog\\themes\\Annie\\layout\\_partial\\plugin\\toc.ejs"
    at new Function (<anonymous>)
    at Object.exports.compile (D:\Blog\node_modules\ejs\lib\ejs.js:242:14)
    at Function.ejsRenderer.compile (D:\Blog\node_modules\hexo-renderer-ejs\lib\renderer.js:11:14)
    at Theme._View.View.View._precompile (D:\Blog\node_modules\hexo\lib\theme\view.js:119:29)
    at Theme._View.View.View (D:\Blog\node_modules\hexo\lib\theme\view.js:13:8)
    at new Theme._View.View (D:\Blog\node_modules\hexo\lib\theme\index.js:37:10)
    at Theme.setView (D:\Blog\node_modules\hexo\lib\theme\index.js:71:20)
    at D:\Blog\node_modules\hexo\lib\theme\processors\view.js:14:14
    at tryCatcher (D:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\Blog\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (D:\Blog\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (D:\Blog\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\Blog\node_modules\bluebird\js\release\promise.js:638:18)
    at D:\Blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at D:\Blog\node_modules\graceful-fs\graceful-fs.js:78:16
INFO  Files loaded in 443 ms
WARN  Partial plugin/toc does not exist. (in _partial\post.ejs)
WARN  Partial post-relate does not exist. (in _partial\post.ejs)
WARN  Partial plugin/toc does not exist. (in _partial\post.ejs)
WARN  Partial post-relate does not exist. (in _partial\post.ejs)
WARN  Partial plugin/toc does not exist. (in _partial\post.ejs)
WARN  Partial post-relate does not exist. (in _partial\post.ejs)
WARN  Partial plugin/toc does not exist. (in _partial\post.ejs)
WARN  Partial post-relate does not exist. (in _partial\post.ejs)
WARN  Partial plugin/toc does not exist. (in _partial\post.ejs)
WARN  Partial post-relate does not exist. (in _partial\post.ejs)
INFO  Generated: index.html
INFO  1 files generated in 402 ms
```

**Comment by Sariay** [comment]
@Symbolk 

主题代码应该没问题，目前我也没有找到解决办法！

你可以尝试新建文件夹，**hexo init**重新初始化，再重新使用主题。

**Comment by Symbolk** [comment]
一切重新开始就没问题了，可能是和我以前的某个版本有冲突吧，多谢回复~
